config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "login", to: "sessions#destroy"

  resource :users, only: [:update, :edit, :destroy], path: "account", as: "account"

  get "/profile", to: "users#show"

  resources :confirmations, only: [:new, :create, :edit], param: :confirmation_token

  resource :password_resets, only: [:new, :create, :edit, :update]

  resource :password, only: [:edit, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div data-controller="flash" class="flex top-5 <%= classes_for_flash(key) %> py-3 px-5 rounded-lg">
    <button type="button" data-action="flash#dismiss">
      <svg xmlns="http://wwww.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>

    <div class="ml-4"><%= value %></div>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<!-- app/views/shared/_form_errors.html.erb -->
<% if object.errors.any? %>
  <ul class="mb-2 text-red-600 rounded-md" id="error-messages">
    <% object.errors.full_messages.each do |message| %>
      <li class="text-sm"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<header class="relative flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full bg-white text-sm py-4 dark:bg-gray-800">
  <nav class="max-w-[85rem] w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between" aria-label="Global">
    <div class="flex items-center justify-between">
      <%= link_to "Brand", root_path, class: "flex-none text-xl font-semibold dark:text-white" %>
      <div class="sm:hidden">
        <button type="button" class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-x-2 rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-gray-700 dark:text-white dark:hover:bg-white/10 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" data-hs-collapse="#navbar-with-mega-menu" aria-controls="navbar-with-mega-menu" aria-label="Toggle navigation">
          <svg class="hs-collapse-open:hidden flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" x2="21" y1="6" y2="6"/><line x1="3" x2="21" y1="12" y2="12"/><line x1="3" x2="21" y1="18" y2="18"/></svg>
          <svg class="hs-collapse-open:block hidden flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
        </button>
      </div>
    </div>
    <div id="navbar-with-mega-menu" class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
      <div class="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:ps-5">
        <a class="font-medium text-blue-500 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#" aria-current="page">Landing</a>
        <a class="font-medium text-gray-600 hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-500 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">Work</a>
        <a class="font-medium text-gray-600 hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-500 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">Blog</a>
        <div 
          class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none]"
          data-controller="dropdown"
        >
          <% if user_signed_in?%>
            <button 
              id="hs-mega-menu-basic-dr"
              type="button"
              class="flex items-center w-full text-gray-600 hover:text-gray-400 font-medium dark:text-gray-400 dark:hover:text-gray-500"
              data-dropdown-target="button"
              data-action="click->dropdown#toggle keydown.esc->dropdown#toggle click@window->dropdown#hide"
            >
              Account
              <svg class="ms-1 flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>
            </button>

            <div
              class="absolute right-0 origin-top-right w-48 shadow-xl rounded z-1 hidden"
              role="menu"
              data-dropdown-target="menu"
              data-transition-enter="transition ease-out duration-100"
              data-transition-enter-start="transform opacity-0 scale-95"
              data-transition-enter-end="transform opacity-100 scale-100"
              data-transition-leave="transition ease-in duration-75"
              data-transition-leave-start="transform opacity-100 scale-100"
              data-transition-leave-end="transform opacity-0 scale-95"
              aria-orientation="vertical" aria-labelledby="dropdown_example"
            >
              <%= link_to "Profile", profile_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300" %>
              <%= link_to "Chat History", "#", class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300" %>
              <%= link_to "Log out", login_path, data: { "turbo-method": :delete }, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300" %>
            </div>
          <% else %>
            <%= link_to "Log in", login_path %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>